blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blogs/', BlogListView.as_view(), name='blogs'),
    path('blogs/<int:pk>', BlogDetailView.as_view(), name='blogs_item'),
    path('blogs/create', BlogCreateView.as_view(), name='blog_create'),
    path('blogs/update/<int:pk>', BlogUpdateView.as_view(), name='blog_update'),
    path('blogs/delete/<int:pk>', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blogs/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils.text import slugify
import datetime

NULLABLE = {'null': True, 'blank': True}

class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='заголовок')
    body = models.TextField(verbose_name='содержимое', **NULLABLE)
    slug = models.CharField(max_length=100, verbose_name='slug', **NULLABLE)
    preview = models.ImageField(upload_to='blog/', verbose_name='изображение', **NULLABLE)
    created_at = models.DateField(verbose_name='Создан', default=datetime.date.today)
    publication = models.BooleanField(verbose_name='опубликован', default=False)
    views_count = models.IntegerField(verbose_name='количество просмотров', default=0)

    def inc_view_count(self):
        self.views_count += 1
        return self.views_count

    def save(self, *args, **kwargs):  # new
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.title}\nСоздан: {self.created_at}'

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'
        ordering = ('title',)

blog/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DeleteView, UpdateView, CreateView, DetailView
from pytils.translit import slugify
from django.contrib.auth.mixins import PermissionRequiredMixin
from blog.models import Blog


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(publication=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data()
        context_data['title'] = context_data['object']
        return context_data

    def get_object(self, queryset=None):
        post = super().get_object(queryset)
        post.inc_views_count()
        post.save()
        return post


class BlogCreateView(PermissionRequiredMixin, CreateView):
    model = Blog
    fields = ('title', 'body',)
    success_url = reverse_lazy('blog:blogs')
    permission_required = 'blog.add_blog'

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)


class BlogUpdateView(PermissionRequiredMixin, UpdateView):
    model = Blog
    fields = ('title', 'body', 'preview', 'publication')
    permission_required = 'blog.change_blog'

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:blogs_item', args=[self.kwargs.get('pk')])


class BlogDeleteView(PermissionRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blogs')
    permission_required = 'blog.delete_blog'

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}
{% load my_filter %}
{% block content %}
<div class="row">
        <div class="card mb-5">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p> Хотите удалить блог? "{{ object.title }}"</p>
                    {% if perms.blog.delete_blog %}
                    <button type="submit" class="btn btn-success">Подтвердить</button>
                    {% endif %}
                    <a href="{% url 'blog:blogs' %}" class="btn btn-warning">Отмена</a>
                </form>
            </div>
        </div>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load my_filter %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="card mb-4">
            <div class="card-body">
                <div class="d-flex justify-content-between align-items-center">
                    <p>{{ object.title }} {{ object.slug }}</p><br>
                </div>
            </div>
        </div>
        <div class="card mb-4">
            <div class="card-body">
                <div class="d-flex justify-content-between align-items-center">
                    <p>{{ object.body }}</p><br>
                </div>
            </div>
        </div>
    </div>
    <br>
    <br>
    <div class="card-footer">
        Просмотры: {{ object.views_count }}
        <a href="{% url 'blog:blogs' %}" class="btn btn-sm btn-outline-secondary">Back</a>
    </div>
</div>
{{ object.inc }}
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        {% if object %}
                         Сохранить
                        {% else %}
                         Создать</button>
                        {% endif %}
                </form>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}
{% load my_filter %}
{% block content %}
<div class="col-12">
    {% if perms.blog.add_blog %}
    <a href="{% url 'blog:blog_create' %}" class="btn btn-sm btn-outline-secondary m-1">Create new blog></a>
    {% endif %}
    <div class="row text-center mx-5">
        {% for object in object_list %}
        <div class="col-4">
            <div class="card shadow-sm">
                <svg class="bd-placeholder-img card-img-top" width="100%" height="225"
                     xmlns="http://www.w3.org/2000/svg"
                     role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice"
                     focusable="false">
                    <title>Placeholder</title>
                    <rect width="100%" height="100%" fill="#55595c"/>
                    <text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text>
                </svg>

                <div class="card-body">
                    <p class="card-text">{{ object|title }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="{% url 'blog:blogs_item' object.pk %}"
                               class="btn btn-sm btn-outline-secondary m-1">View</a>
                            {% if perms.blog.change_blog %}
                            <a href="{% url 'blog:blog_update' object.pk %}"
                               class="btn btn-sm btn-outline-secondary m-1">Edit</a>
                            {% endif %}
                            {% if perms.blog.delete_blog %}
                            <a href="{% url 'blog:blog_delete' object.pk %}"
                               class="btn btn-sm btn-outline-secondary m-1">Delete</a>
                            {% endif %}
                            </button>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        {% endfor %}
    </div>
    {% endblock %}