blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blogs/', BlogListView.as_view(), name='blogs'),
    path('blogs/<int:pk>', BlogDetailView.as_view(), name='blogs_item'),
    path('blogs/create', BlogCreateView.as_view(), name='blog_create'),
    path('blogs/update/<int:pk>', BlogUpdateView.as_view(), name='blog_update'),
    path('blogs/delete/<int:pk>', BlogDeleteView.as_view(), name='blog_delete'),
]

catalog/urls.py
from catalog.apps import CatalogConfig
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.views import ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView, ProductDeleteView,  contact

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('contacts/', contact, name='contacts'),
    path('product/<int:pk>', ProductDetailView.as_view(), name='view_product'),
    path('product/create/', ProductCreateView.as_view(), name='create_product'),
    path('product/update/<int:pk>', ProductUpdateView.as_view(), name='update_product'),
    path('product/product_item/<int:pk>', cache_page(60)(ProductDetailView.as_view()), name='product_item'),
    path('product/product/delete/<int:pk>', ProductDeleteView.as_view(), name='product_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blogs/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView, PasswordResetView, LoginView
from django.urls import path
from django.views.generic import TemplateView

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, EmailVerify, PasswordRecoveryView, ExtraLoginView

app_name = UsersConfig.name




urlpatterns = [
    path('recovery/', PasswordRecoveryView.as_view(template_name='users/restore_pass.html'), name='recovery'),
    path('login/', ExtraLoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('confirm_email/', TemplateView.as_view(template_name='users/confirm_email.html'),
         name='confirm_email'),
    path('verify_email/<uidb64>/<token>/', EmailVerify.as_view(), name='verify_email'),
    path('invalid_verify/', TemplateView.as_view(template_name='users/invalid_verify.html'),
         name='invalid_verify'),
    path('reset/<uidb64>/<token>/', PasswordResetView.as_view(), name='reset'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'null': True, 'blank': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')
    email_verify = models.BooleanField(default=False)

    phone = models.CharField(max_length=35, verbose_name='телефон', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    country = models.CharField(max_length=60, verbose_name='страна')

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

users/forms.py
from django import forms
from django.contrib.auth import authenticate

from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordResetForm, AuthenticationForm as Auth
from django.core.exceptions import ValidationError


from catalog.forms import StyleFormMixin
from users.models import User
from users.utils import send_email_for_verify


class AuthenticationForm(Auth):
    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username is not None and password:
            self.user_cache = authenticate(
                self.request,
                username=username,
                password=password,
            )

            if self.user_cache is None:
                raise self.get_invalid_login_error()
            else:
                if not self.user_cache.email_verify:
                    send_email_for_verify(self.request, self.user_cache)
                    raise ValidationError(
                        'Email not verify, check your email',
                        code='invalid_login',
                    )
                else:
                    self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data



class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')




class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'avatar', 'country')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()


class UserRecoveryForm(StyleFormMixin, PasswordResetForm):
    email = forms.EmailField(max_length=100)

users/views.py
from django.conf import settings
from django.contrib.auth.views import LoginView
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordResetConfirmView, PasswordResetView
from django.core.mail import send_mail
import random
from django.shortcuts import redirect, render

from django.urls import reverse_lazy, reverse
from django.utils.http import urlsafe_base64_decode
from django.views import View
from django.views.generic import CreateView, UpdateView
from django.contrib.auth.tokens import default_token_generator as token_generator

from config.settings import EMAIL_HOST_USER
from users.forms import UserProfileForm, UserRecoveryForm, UserRegisterForm
from users.models import User
from django.core.exceptions import ValidationError

from users.utils import send_email_for_verify

class ExtraLoginView(LoginView):
    form_class = AuthenticationForm
# class LoginView(BaseLoginView):
#     template_name = 'users/login.html'
#     form_class = AuthenticationForm


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:confirm_email')


    # def form_valid(self, form):
    #     new_user = form.save()
    #     send_mail(
    #         subject='поздравляем с регистрацией',
    #         message='вы зарегистрированы',
    #         form_email=settings.EMAIL_HOST_USER,
    #         recipient_list=[new_user.email]
    #     )
    #     return super().form_valid(form)


    def post(self, request, **kwargs):
        form = UserRegisterForm(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            # email = form.cleaned_data.get('email')
            # password = form.cleaned_data.get('password1')
            # user = authenticate(email=email, password=password)
            send_email_for_verify(request, user)
            return redirect('users:confirm_email')
        context = {
            'form': form
        }
        return render(request, self.template_name, context)


class ProfileView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class EmailVerify(View):

    def get(self, request, uidb64, token):
        user = self.get_user(uidb64)

        if user is not None and token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            login(request, user)
            return redirect('/')
        return redirect('users:invalid_verify')

    @staticmethod
    def get_user(uidb64):
        try:
            # urlsafe_base64_decode() decodes to bytestring
            uid = urlsafe_base64_decode(uidb64).decode()
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError,
                User.DoesNotExist, ValidationError):
            user = None
        return user


class PasswordRecoveryView(PasswordResetView):
    template_name = 'users/restore_pass.html'
    email_template_name = 'users/reset_email.html',
    success_url = reverse_lazy('users:login')
    from_email = EMAIL_HOST_USER
    form_class = UserRecoveryForm



class PasswordResetView(PasswordResetConfirmView):
    post_reset_login = True
    template_name = "users/password_reset_confirm.html"
    success_url = reverse_lazy('users:login')


# def forgot_password(request):
#     if request.method == 'POST':
#         email = request.POST.get('user_email')
#         try:
#             user = User.objects.get(email=email)
#             new_password = ''.join([str(random.randint(0, 9)) for _ in range(8)])
#             send_mail(
#                 subject='New password',
#                 message=f'Your new password {new_password}',
#                 from_email=EMAIL_HOST_USER,
#                 recipient_list=[user.email]
#             )
#             user.set_password(new_password)
#             user.save()
#             return redirect(reverse('users:login'))
#         except Exception:
#             message = 'We can not find user with this email'
#             contex = {
#                 'message': message
#             }
#             return render(request, 'users/forgot_password.html', contex)
#     else:
#         return render(request, 'users/forgot_password.html')

users/templates/users/confirm_email.html
{% extends 'catalog/base.html' %}

{% block content %}

    <div class="row">
        <p>Пожалуйста проверьте свою почту чтобы завершить регистрацию</p>
    </div>
{% endblock %}

users/templates/users/forgot_password.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container mt-5 mb-5">
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header"></div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div>
                            <h6>{{message}}</h6>
                        </div>
                        <input type="email" name="user_email">
                        <input type="submit" value="Отправить">
                    </form>
                </div>
                <div class="card-footer"></div>
            </div>

        </div>

    </div>
</div>

{% endblock %}

users/templates/users/invalid_verify.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="row">
    <p>Пожалуйста проверьте свою почту {{ user.post }} и перейдите по ссылке, чтобы завершить регистрацию</p>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="row">
    <div class="col-3">
        <div class="col-6">
            <div class="card">
                <div class="card-header"></div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" cls="btn btn-success">Вход</button>
                    </form>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'catalog/base.html' %}
{% load i18n static %}

{#{% block extrastyle %}{{ block.super }}
<link rel="stylesheet" href="{% static " admin/css/forms.css" %}">{% endblock %}#}
{#{% block breadcrumbs %}#}
{#
<div class="breadcrumbs">#}
    {#<a href="{% url 'admin:index' %}">{% translate 'Home' %}</a>#}
    {#&rsaquo; {% translate 'Password reset confirmation' %}#}
    {#
</div>#}
{#{% endblock %}#}

{% block content %}

{% if validlink %}

<p>{% translate "Please enter your new password twice so we can verify you typed it in correctly." %}</p>
<div class="col-lg-6">
    <form method="post">{% csrf_token %}
        <fieldset class="module aligned">
            {{ form.user.get_username }}
            <br>
            <br>
            <div class="form-row field-password1">
                {{ form.new_password1.errors }}
                <label for="id_new_password1">{% translate 'New password: ' %} </label>
                {{ form.new_password1 }}
            </div>
            <br>
            <div class="form-row field-password2">
                {{ form.new_password2.errors }}
                <label for="id_new_password2">{% translate 'Confirm password: ' %} </label>
                {{ form.new_password2 }}
            </div>
            <br>
            <input type="submit" value="{% translate 'Change my password' %}">
        </fieldset>
    </form>


    {% else %}

    <p>{% translate "The password reset link was invalid, possibly because it has already been used. Please request a
        new password reset." %}</p>

    {% endif %}
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="card mb-5">
            <div class="card-header">
                <h3 class="card-title">
                    Регистрация
                </h3>
            </div>
            <div class="card-body">
                <div class="row">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-success"
                           value="Регистрация">
                    <a href="{% url 'catalog:index' %}" class="btn btn-primary">Back</a>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/reset_email.html
{% autoescape off %}
Уважаемый {{ user.username }}!
Вы отправили запрос на сброс пароля. Чтобы выполнить сброс, пройдите
по этому интернет-адресу :

{{ protocol }}://{{ domain }}{% url 'users:reset' uidb64=uid token=token %}
{% endautoescape %}

users/templates/users/restore_pass.html
{% extends 'catalog/base.html' %}
{% load static %}
{% block content %}


<div class="col-12 blog-main">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-8">
            <div class="card-header">
                <h3>Восстановление пароля</h3>
            </div>
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-success" value="Выслать пароль">
        </div>
    </form>
</div>

{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="card mb-5">
            <div class="card-header">
                <h3 class="card-title">
                    Профиль
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class="btn btn-success"
                       value="Сохранить">
                <a href="{% url 'catalog:index' %}" class="btn btn-primary">Back</a>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/verify_email.html
{% autoescape off %}

Здравствуйте {{ user.get_username }},
пожалуйста перейдите по ссылке, чтобы закончить регистрацию
http://{{ domain }}{% url 'users:verify_email' uidb64=uid token=token %}

{% endautoescape %}