blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blogs/', BlogListView.as_view(), name='blogs'),
    path('blogs/<int:pk>', BlogDetailView.as_view(), name='blogs_item'),
    path('blogs/create', BlogCreateView.as_view(), name='blog_create'),
    path('blogs/update/<int:pk>', BlogUpdateView.as_view(), name='blog_update'),
    path('blogs/delete/<int:pk>', BlogDeleteView.as_view(), name='blog_delete'),
]

catalog/urls.py
from catalog.apps import CatalogConfig
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.views import ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView, ProductDeleteView,  contact

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('contacts/', contact, name='contacts'),
    path('product/<int:pk>', ProductDetailView.as_view(), name='view_product'),
    path('product/create/', ProductCreateView.as_view(), name='create_product'),
    path('product/update/<int:pk>', ProductUpdateView.as_view(), name='update_product'),
    path('product/product_item/<int:pk>', cache_page(60)(ProductDetailView.as_view()), name='product_item'),
    path('product/product/delete/<int:pk>', ProductDeleteView.as_view(), name='product_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blogs/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView, PasswordResetView, LoginView
from django.urls import path
from django.views.generic import TemplateView

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, EmailVerify, PasswordRecoveryView, ExtraLoginView

app_name = UsersConfig.name




urlpatterns = [
    path('recovery/', PasswordRecoveryView.as_view(template_name='users/restore_pass.html'), name='recovery'),
    path('login/', ExtraLoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('confirm_email/', TemplateView.as_view(template_name='users/confirm_email.html'),
         name='confirm_email'),
    path('verify_email/<uidb64>/<token>/', EmailVerify.as_view(), name='verify_email'),
    path('invalid_verify/', TemplateView.as_view(template_name='users/invalid_verify.html'),
         name='invalid_verify'),
    path('reset/<uidb64>/<token>/', PasswordResetView.as_view(), name='reset'),
]

catalog/models.py
import datetime
from django.db import models

from users.models import User

NULLABLE = {'null': True, 'blank': True}

class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(verbose_name='описание'),
    create_at = models.DateField(verbose_name='на удаление', default=datetime.date.today)

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('name',)


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(verbose_name='описание')
    preview = models.ImageField(upload_to='product/', verbose_name='изображение', **NULLABLE)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name='категория')
    cost = models.FloatField(verbose_name='цена')
    create_data = models.DateField(verbose_name='на удаление', default=datetime.date.today)
    data_change = models.DateField(verbose_name='последнее изменение', default=datetime.date.today)
    product_is_publicated = models.BooleanField(verbose_name='опубликован', default=False)

    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='владелец', **NULLABLE)

    def __str__(self):
        return f"{self.name} * {self.cost}"

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ('name',)
        permissions = [
            (
                'product_is_publicated',
                'Can publish product'
            ),
            (
                'description',
                'Can edit description'
            ),
            (
                'category',
                'Can change category'
            )
        ]


class Version(models.Model):
    version_product = models.ForeignKey(Product, on_delete=models.CASCADE)
    version_number = models.IntegerField(verbose_name='номер версии')
    version_name = models.CharField(max_length=100, verbose_name='название версии')
    version_is_active = models.BooleanField(default=False, verbose_name='активная версия')

    def __str__(self):
        return f"{self.version_name} v.{self.version_number}"

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'
        ordering = ('version_product',)

catalog/forms.py
from django import forms

from catalog.models import Product, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    forbidden_words = {'казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар'}

    @staticmethod
    def has_forbidden_words(field_content: str) -> bool:
        return bool(len(ProductForm.forbidden_words & set(field_content.split())))

    class Meta:
        model = Product
        exclude = ('data_created', 'data_change',)

    class ModeratorProductForm(forms.ModelForm):
        class Meta:
            model = Product
            fields = ('name', 'description', 'category')

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            for field_name, field in self.fields.items():
                field.widget.attrs['class'] = 'form-control'
            self.fields["product_is_published"].widget.attrs['class'] = 'form-check-input'

    def clean_product_name(self):
        clean_data = self.cleaned_data['name']

        if self.has_forbidden_words(clean_data):
            raise forms.ValidationError(f'Поле "Наименование" не должно содержать '
                                        f'слов - {", ".join(ProductForm.forbidden_words)}.')

        return clean_data

    def clean_product_description(self):
        clean_data = self.cleaned_data['description']

        if self.has_forbidden_words(clean_data):
            raise forms.ValidationError(f'Поле "Описание" не должно содержать '
                                        f'слов - {", ".join(ProductForm.forbidden_words)}.')

        return clean_data


class ProductVersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

    def clean_version_is_active(self):
        version_is_active = self.cleaned_data.get('version_is_active')
        product = self.cleaned_data.get('version_product')
        Version.objects.filter(version_product=product).exclude(id=self.instance.id).update(version_is_active=False)
        return version_is_active

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.core.mail import send_mail
from django.forms import inlineformset_factory
from django.shortcuts import render
from django.urls import reverse_lazy

from catalog.forms import ProductForm, ProductVersionForm
from catalog.models import Product, Version
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView

from catalog.utils2 import get_categories
from config import settings
from users.models import User


class ProductListView(ListView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:index')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data()
        version_list = Version.objects.all()
        context_data['formset'] = version_list
        return context_data

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(product_is_publicated=True)
        return queryset


class ProductDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Product
    permission_required = 'catalog.view_product'

    # def get_context_data(self, **kwargs):
    #     context_data = super().get_context_data()
    #     context_data['title'] = context_data['object']
    #     return context_data


def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    self.object = super().get_object()
    if self.object.owner == self.request.user or self.request.user.groups.filter(
            name='Модератор').exists():
        context["edit"] = True
    else:
        context["edit"] = False
    return context


class ProductCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:index')
    permission_required = 'catalog.add_product'

    def get_initial(self):
        return {'user': self.request.user}

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)

    # def get_initial(self):
    #     initials = super().get_initial()
    #     initials['version_user'] = User.objects.get(email=self.request.user)
    #     return initials


class ProductDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:index')
    permission_required = 'catalog.delete_product'


class ProductUpdateView(UserPassesTestMixin, LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:index')
    permission_required = 'catalog.change_product'

    def test_func(self):
        return self.get_object().owner == self.request.user
    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(**kwargs)
        version_formset = inlineformset_factory(Product, Version, form=ProductVersionForm, fields='__all__', extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = version_formset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = version_formset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


def contact(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        send_mail(f'You have new message from {name}({phone})', message,
                  settings.EMAIL_HOST_USER, ['tishyulya.1@yandex.ru'])
        print(f'You have new message from {name}({phone}): {message}')
    context = {
        'title': 'Контакты'
    }
    return render(request, 'catalog/contact.html', context)


def categories_list(request):
    context = {
        "objects_list": get_categories()
    }
    return render(request, 'catalog/categories_list.html', context=context)

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">

    <title>{{ title }}</title>


    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

</head>
<body>

<header>
    <div class="collapse" id="navbarToggleExternalContent" data-bs-theme="dark">
        <div class="bg-dark p-4">
            <h4 class="text-white">Меню</h4>
            <ul class="list-unstyled">
                <li><a href="{% url 'catalog:index' %}" class="text-white">Главная</a></li>
                <li><a href="{% url 'catalog:contacts' %}" class="text-white">Контакты</a></li>
                <li><a href="{% url 'blog:blogs' %}" class="text-white">Блог</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'users:profile' %}" class="text-white">Профиль</a></li>
                    <li><a href="{% url 'users:logout' %}" class="text-white">Выход</a></li>
                {% else %}
                    <li><a href="{% url 'users:login' %}" class="text-white">Вход</a></li>
                    <li><a href="{% url 'users:register' %}" class="text-white">Регистрация</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
    <nav class="navbar navbar-dark bg-dark">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </nav>
</header>

<main role="main">

    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <h1 class="fw-light">{{ title }}</h1>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">
            {% block content %}
            {% endblock %}

        </div>
    </div>
    </div>

</main>

<footer class="container bg-body-tertiary">
    <footer class="py-5">
        <div class="row">
            <div class="col-6 col-md-2 mb-3">
                <h5>Section</h5>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Home</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Features</a>
                    </li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Pricing</a>
                    </li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">FAQs</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">About</a>
                    </li>
                </ul>
            </div>

            <div class="col-6 col-md-2 mb-3">
                <h5>Section</h5>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Home</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Features</a>
                    </li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Pricing</a>
                    </li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">FAQs</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">About</a>
                    </li>
                </ul>
            </div>

            <div class="col-6 col-md-2 mb-3">
                <h5>Section</h5>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Home</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Features</a>
                    </li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Pricing</a>
                    </li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">FAQs</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">About</a>
                    </li>
                </ul>
            </div>

            <div class="col-md-5 offset-md-1 mb-3">
                <form>
                    <h5>Subscribe to our newsletter</h5>
                    <p>Monthly digest of what's new and exciting from us.</p>
                    <div class="d-flex flex-column flex-sm-row w-100 gap-2">
                        <label for="newsletter1" class="visually-hidden">Email address</label>
                        <input id="newsletter1" type="text" class="form-control" placeholder="Email address">
                        <button class="btn btn-primary" type="button">Subscribe</button>
                    </div>
                </form>
            </div>
        </div>

        <div class="d-flex flex-column flex-sm-row justify-content-between py-4 my-4 border-top">
            <p>&copy; 2023 Company, Inc. All rights reserved.</p>
            <ul class="list-unstyled d-flex">
                <li class="ms-3"><a class="link-body-emphasis" href="#">
                    <svg class="bi" width="24" height="24">
                        <use xlink:href="#twitter"/>
                    </svg>
                </a></li>
                <li class="ms-3"><a class="link-body-emphasis" href="#">
                    <svg class="bi" width="24" height="24">
                        <use xlink:href="#instagram"/>
                    </svg>
                </a></li>
                <li class="ms-3"><a class="link-body-emphasis" href="#">
                    <svg class="bi" width="24" height="24">
                        <use xlink:href="#facebook"/>
                    </svg>
                </a></li>
            </ul>
        </div>
    </footer>

</footer>



<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
        integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
        crossorigin="anonymous"></script>


</body>
</html>

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}
{% load my_filter%}
{% block content %}
<div>

    <h1 class="container text-center pt-5">
        Список Товаров
    </h1>
    <div class="py-5">
        <div class="container">

            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

                {% for object in objects_list %}

                <div class="col">
                    <div class="card shadow-sm">
                        <img src="{{ object.product_image|my_media }}" alt="image" height=200px width=300px>
                        <div class="card-body">
                            <p class="card-text">{{ object.name }}</p>
                            <p class="card-text">{{ object.description }}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'categories_list' %}">Categories</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'product_list' %}">Product list</a>
                </li>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>


                {% endfor %}

            </div>
        </div>
    </div>


</div>


{% endblock %}

catalog/templates/catalog/contact.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    <div class="col-mb-4">
        <div class="card-body">
            <div class="card shadow-sm">
                <p class="card-text">
                    Офис Мск<br>
                    Офис Спб<br>
                </p>
            </div>
        </div>
    </div>
</div>
<div class="col-mb-4">
    <div class="card-body">
        <div class="card shadow-sm">
            <h2>Напишите нам</h2>
            <form method="post">
                {% csrf_token %}
                <input class="form-control" name="name"/>
                <input class="form-control" name="email"/>
                <textarea class="form-control" name="message"></textarea>
                <button type="submit" class="btn btn-primary form-control">Отправить</button>
            </form>
            </p>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product.html
{% extends 'catalog/base.html' %}
{% block content %}
<!--<div class="card" style="width: 18rem;">-->
<!--  <img src="{{product.image}}" class="card-img-top" alt="...">-->
<!--  <div class="card-body">-->
<!--    <div class="card text-center">-->
<!--    <h5 class="card-title">{{ product }}</h5>-->
<!--    <p class="card-text">Небольшой пример текста, который должен основываться на названии карточки и составлять основную часть содержимого карты.</p>-->
<!--    <a href="#" class="btn btn-primary">Перейти куда-нибудь</a>-->
<!--  </div>-->
<!--</div>-->
<div class="card text-center">
    <div class="card-header">
        <div class="card" style="width: 18rem;">
            <img src="{{product.image}}" class="card-img-top" alt="...">
            <div class="card-body">
                <p class="card-text_center">Небольшой пример текста, который должен основываться на названии карточки и
                    составлять основную часть содержимого карточки.</p>
            </div>
        </div>
    </div>
    <div class="card-body">
        <h5 class="card-title">{{ product1 }}</h5>
        <p class="card-text">С вспомогательным текстом ниже в качестве естественного перехода к дополнительному
            контенту.</p>
        <a href="#" class="btn btn-primary">Перейти куда-нибудь</a>
    </div>
</div>
</div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
% extends 'catalog/base.html' %}
{% load my_filter %}
{% block content %}
    <div class="row">
        <div class="card mb-5">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    Нажмите "Да" для подтверждения удаления продукта "{{ object }}" <br><br>
                    <input type="submit" class="btn btn-success" value="Да">
                     <a href="{% url 'catalog:index' %}" class="btn btn-primary">Back</a>
                </form>
            </div>
        </div>
    </div>
 {% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_filter %}
<div class="card text-center">
    <div class="card-header">
        <div class="card" style="width: 18rem;">
            <img src="{{product.image}}" class="card-img-top" alt="...">
            <div class="card-body">
                <p class="card-text_center">Информация о продукте
                    </p>
            </div>
        </div>
    </div>
    <div class="card-body">
        <h5 class="card-title">{{ product1 }}</h5>
        <p class="card-text">С вспомогательным текстом ниже в качестве естественного перехода к дополнительному
            контенту.</p>
        <a href="#" class="btn btn-primary">Перейти куда-нибудь</a>
    </div>
</div>
</div>
{% endblock %}{

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% load my_filter %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {{ form.as_p }}
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary" Создать
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
 <div class="col-6">
                <div class="card-header">
                    <h3>Версии продукта</h3>
                </div>
                {{ formset.management_form }}
                {% for form in formset.forms %}
                    {{ form.as_p }}
                    {% if not forloop.last %}
                        <hr>
                        <hr>
                    {% endif %}
                {% endfor %}
            </div>
        </form>
    </div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_filter %}
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'catalog:create_product' %}">Добавить продукт</a>
</div>
<div class="row text-center mx-5">
    {% for object in object_list %}
    <div class="col-4">
        <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg"
                role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">
                <title>Placeholder</title>
                <rect width="100%" height="100%" fill="#55595c" />
                <text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text>
            </svg>

            <div class="card-body">
                <p class="card-text">{{ object }}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        {% if perms.catalog.view_product %}
                            <a href="{% url 'catalog:view_product' object.pk %}"
                               class="btn btn-sm btn-outline-secondary m-1">View</a>
                        {% endif %}
                        {% if perms.catalog.change_product %}
                            <a href="{% url 'catalog:update_product' object.pk %}"
                               class="btn btn-sm btn-outline-secondary m-1">Edit</a>
                        {% endif %}
                        {% if perms.catalog.delete_product %}
                            <a href="{% url 'catalog:product_delete' object.pk %}"
                               class="btn btn-sm btn-outline-secondary m-1">Delete</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

    </div>
    {% endfor %}
</div>


{% endblock %}